app/Models/Category.php
<?php

namespace App\Models;

use App\Enums\MediaCollection;
use App\Enums\MediaConversion;
use App\Enums\MediaType;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Category extends Model implements HasMedia
{
    use SoftDeletes;
    use InteractsWithMedia;
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description', 'status', 'template_id'];

    /**
     * Indicates custom attributes to append to model.
     *
     * @var array
     */
    public $appends = ['icon', 'backdrop'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'status' => 'boolean',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['media'];

    /**
     * Registers media collections
     *
     * @return void
     */
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection(MediaCollection::ICON)
            ->useFallbackUrl('/img/placeholders/icon.png')
            ->acceptsMimeTypes(MediaType::ICONS)
            ->singleFile();

        $this->addMediaCollection(MediaCollection::WHITEICON)
            ->useFallbackUrl('/img/placeholders/white-icon.png')
            ->acceptsMimeTypes(MediaType::ICONS)
            ->singleFile();

        $this->addMediaCollection(MediaCollection::BACKDROP)
            ->useFallbackUrl('/img/placeholders/backdrop.jpg')
            ->acceptsMimeTypes(MediaType::IMAGES)
            ->singleFile();
    }

    /**
     * Register media conversions.
     *
     * @return void
     */
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion(MediaConversion::THUMB)
            ->width(100)
            ->height(100)
            ->sharpen(10)
            ->queued();

        $this->addMediaConversion(MediaConversion::STANDARD)
            ->width(400)
            ->height(400)
            ->sharpen(10)
            ->queued();
    }

    /**
     * Scope a query to only include active categories.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query)
    {
        return $query->where('status', true);
    }

    /**
     * Get full URL for the category's icon.
     *
     * @return string
     */
    public function getIconAttribute()
    {
        return $this->getFirstMediaUrl(MediaCollection::ICON);
    }

    /**
     * Get full URL for the category's white icon.
     *
     * @return string
     */
    public function getWhiteIconAttribute()
    {
        return $this->getFirstMediaUrl(MediaCollection::WHITEICON);
    }

    /**
     * Get full URL for the category's Backdrop.
     *
     * @return string
     */
    public function getBackdropAttribute()
    {
        return $this->getFirstMediaUrl(MediaCollection::BACKDROP);
    }


    /**
     * Get the related template for the category.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function template()
    {
        return $this->belongsTo(Template::class);
    }

    /**
     * Get all the listings for the category.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function businessListings()
    {
        return $this->hasMany(BusinessListing::class);
    }

    /**
     * Get all the properties for the category.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function properties()
    {
        return $this->hasMany(CategoryProperty::class);
    }
}

resources/views/index.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('styles')
  <link href="{{ asset('css/theme-home.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('content')
@include('includes.nav')
<div class="main-container">
    <section class="imagebg home height-100" data-overlay="7">
        <div
            class="background-image-holder"
            style="background-image: url({{ mapMonthBackground('home') }})"
        ></div>
        <div class="container pos-vertical-center">
            <div class="row align-items-center mb-4 home-search">
                <div class="col-12">
                    <div class="d-flex justify-content-center">
                        <div class="hidden-xs hidden-sm">
                            <img src="{{ asset('img/cn-logo-light-2.png') }}" class="img-logo mr-4">
                        </div>
                        <form action="{{ route('search') }}" method="GET" class="w-100">
                            <div class="input-group search-bar mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon3">Search</span>
                                </div>
                                <input type="text" class="form-control" name="query" placeholder="products, services or business" aria-label="Recipient's username" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit" id="button-addon2">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-4 col-lg-4 col-xl-4 mb-4 mb-lg-0 mb-md-0">
                    <div class="card bg-dark mb-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="imagebg">
                                        <a href="#">
                                            <div
                                                class="background-image-holder"
                                                style="background-image: url({{ asset('img/home-1.jpg') }})">
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <a href="#" class="card-title type-bold mb-1">
                                        {{ truncate('Attend Africa’s Largest Virtual Business Fair', 25) }}
                                    </a>
                                    <p class="mb-2 text-paragraph">
                                        <small class="card-text">
                                            {{ truncate('August 27-28, 2020. Refer a friend and win a laptop.', 50) }}
                                        </small>
                                    </p>
                                    <a href="#" class="type-uppercase mb-0">
                                        <small class="color-primary type-medium">Learn More</small>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-4 col-lg-4 col-xl-4 mb-4 mb-lg-0 mb-md-0">
                    <div class="card bg-dark mb-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="imagebg">
                                        <a href="#">
                                            <div
                                                class="background-image-holder"
                                                style="background-image: url({{ asset('img/home-2.jpg') }})">
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <a href="#" class="card-title type-bold mb-1">
                                        {{ truncate('Establish the Right Corporate Branding', 25) }}
                                    </a>
                                    <p class="mb-2 text-paragraph">
                                        <small class="card-text">
                                            {{ truncate('Make your business stand out with Platform Branding', 50) }}
                                        </small>
                                    </p>
                                    <a href="#" class="type-uppercase mb-0">
                                        <small class="color-primary type-medium">Learn More</small>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-4 col-lg-4 col-xl-4 mb-4 mb-lg-0 mb-md-0">
                    <div class="card bg-dark mb-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="imagebg">
                                        <a href="#">
                                            <div
                                                class="background-image-holder"
                                                style="background-image: url({{ asset('img/home-3.jpg') }})">
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <a href="#" class="card-title type-bold mb-1">
                                        {{ truncate('Advertise in CN & watch your business grow', 25) }}
                                    </a>
                                    <p class="mb-2 text-paragraph">
                                        <small class="card-text">
                                            {{ truncate('Advertse with CN and watch your business grow', 50) }}
                                        </small>
                                    </p>
                                    <a href="#" class="type-uppercase mb-0">
                                        <small class="color-primary type-medium">Learn More</small>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @if($count = $categories->count())
                <div class="category-slider mt-3 p-2 w-100">
                    <div class="{{ $count > 5 ? 'browse-list' : '' }} category-content">
                        @foreach($categories as $category)
                            <div class="slide">
                                <a
                                    class="d-flex align-items-center"
                                    href="{{ route('categories.index', ['category' => $category]) }}"
                                    title="{{ $category->name }}"
                                >
                                    {{-- <img class="img-fluid mr-2" src="{{ $category->white_icon }}" alt="icon" style="width: 25px;"> --}}
                                    <span class="slick-category-name">{{ truncate($category->name, 17) }}</span>
                                </a>
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>
    </section>

    @include('includes.main-footer')
</div>
@endsection

resources/views/pages.blade.php
@extends('layouts.app')

@section('title', 'Page')

@section('styles')
<link href="{{ asset('css/theme-home.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('content')
	<div class="nav-container">
		<div>
			@include('includes.nav-two')
		</div>
	</div>

	<div class="main-container">
        <div class="container py-5">
            <div class="pages-section">
                <div class="page-title">{{ ucwords($page->title) }}</div>
                <div class="page-subtitle">ConnectNigeria.com</div>
                <div class="page-body">{!! $page->body !!}</div>
            </div>
        </div>
        
        <!-- Adding shadow to the nav bar to make it distinct -->
        <style>
            nav{
                box-shadow: 0 0 10px 1px #00000018;
            }
        </style>

		<section>
			@include('includes.middle-cta', ['category' => $category ?? ''])
		</section>
		<!-- FOOTER CTA -->
		@include('includes.footer-cta', ['category' => $category->id ?? ''])
		<!-- END FOOTER CTA -->

		<!-- FOOTER -->
		@include('includes.footer')
		<!-- FOOTER -->
	</div>
@endsection